logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8082
spring:
  application:
    name: java_server
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/system_database}
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

tenants:
  e-food:
    datasource:
      url: ${E_FOOD_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_food_database}
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
    liquibase:
      change-log: classpath:/db/changelog/e-food/db.changelog-master.yaml

  e-market:
    datasource:
      url: ${E_MARKET_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_market_database}
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
    liquibase:
      change-log: classpath:/db/changelog/e-market/db.changelog-master.yaml
